steps:
    - name: 'gcr.io/cloud-builders/docker'
        args: ['build', '-t', 'gcr.io/grounded-camp-410709/pytorch-latest', '.']
    - name: 'gcr.io/cloud-builders/docker'
        args: ['push', 'gcr.io/grounded-camp-410709/pytorch-latest']